config/routes.rb
Rails.application.routes.draw do

  resources :gurus
  resources :prizes
  resources :picks do
    collection { post :import}
  end

  
  resources :surveys
  resources :votes
  resources :scaffolds
  resources :choreo_regs


  resources :qas, :path => 'qa'

  get 'convention/venue'

  get 'convention/home'

  get 'convention/register'

  get 'convention/agenda_one'

  get 'convention/agenda_two'

  get 'convention/agenda_three'  

  get 'convention/winner'

  get 'convention/faq'

  get 'convention/sponsors'
  
  get  'convention/choreo_full'

  get 'pages/faq'

  get 'pages/congratulations'

  get 'pages/vote_counted'

  get 'tables/congrats'


  resources :tables
  

  root to: 'convention#home'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/Trip.rb
class Trip <ActiveRecord::Base

   CLASS_LIST = ["Sea Plane/Fly Fishing Tour", "Sea Plane/Nature Tour/Dinner"]

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choreo_reg.rb
class ChoreoReg < ApplicationRecord   

  validates_presence_of :song, 
                        :names,
                        :email,
                        :phone
end

app/models/guru.rb
class Guru < ApplicationRecord
end

app/models/pick.rb
class Pick < ApplicationRecord

belongs_to :pick, optional: true


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      pick = find_by_id(row['id']) || new
      pick.attributes = row.to_hash
      pick.save!
    end
  end




end

app/models/prize.rb
class Prize < ApplicationRecord

  has_many :picks
end

app/models/qa.rb
class Qa < ApplicationRecord

  validates_presence_of :question

end

app/models/survey.rb
class Survey < ApplicationRecord


  include Question


end

app/models/table.rb
class Table < ApplicationRecord

  validates_presence_of :company, 
                        :first_name, 
                        :middle_name, 
                        :last_name, 
                        :passport_id, 
                        :date_of_birth, 
                        :street_address, 
                        :city, 
                        :state, 
                        :zip_code, 
                        :mobile_phone, 
                        :email,
                        :preferred_airline




#     def self.search(search)
#   where("company ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR city ILIKE ? OR state ILIKE ? OR juneau_excursion ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
# end


    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |table|
            csv << table.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord

  
end

app/controllers/gurus_controller.rb
class GurusController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "Kristen15", except: [ :new, :create ]

  
  before_action :set_guru, only: [:show, :edit, :update, :destroy]

  # GET /gurus
  # GET /gurus.json
  def index
    @gurus = Guru.all
  end

  # GET /gurus/1
  # GET /gurus/1.json
  def show
  end

  # GET /gurus/new
  def new
    @guru = Guru.new
  end

  # GET /gurus/1/edit
  def edit
  end

  # POST /gurus
  # POST /gurus.json
  def create
    @guru = Guru.new(guru_params)

    respond_to do |format|
      if @guru.save
        format.html { redirect_to pages_vote_counted_path, notice: 'Survey successfully submitted' }
        format.json { render :show, status: :created, location: @guru }
      else
        format.html { render :new }
        format.json { render json: @guru.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gurus/1
  # PATCH/PUT /gurus/1.json
  def update
    respond_to do |format|
      if @guru.update(guru_params)
        format.html { redirect_to @guru, notice: 'Guru was successfully updated.' }
        format.json { render :show, status: :ok, location: @guru }
      else
        format.html { render :edit }
        format.json { render json: @guru.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gurus/1
  # DELETE /gurus/1.json
  def destroy
    @guru.destroy
    respond_to do |format|
      format.html { redirect_to gurus_url, notice: 'Guru was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guru
      @guru = Guru.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guru_params
      params.require(:guru).permit(:a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8, :a9)
    end
end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  before_action :set_qa, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "admin", password: "Kristen15", except: [ :new, :create ]

layout 'form'

  # GET /qas
  # GET /qas.json
  def index
    @qas = Qa.all
    @count= Qa.all.count
  end

  # GET /qas/1
  # GET /qas/1.json
  def show
  end


  # GET /qas/new
  def new
    @qa = Qa.new
  end

  # GET /qas/1/edit
  def edit
  end

  # POST /qas
  # POST /qas.json
  def create
    @qa = Qa.new(qa_params)

    respond_to do |format|
      if @qa.save
        format.html { redirect_to pages_congratulations_path, notice: 'Your Question was submitted' }
        format.json { render :show, status: :created, location: @qa }
      else
        format.html { render :new }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qas/1
  # PATCH/PUT /qas/1.json
  def update
    respond_to do |format|
      if @qa.update(qa_params)
        format.html { redirect_to @qa, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @qa }
      else
        format.html { render :edit }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qas/1
  # DELETE /qas/1.json
  def destroy
    @qa.destroy
    respond_to do |format|
      format.html { redirect_to qas_url, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qa
      @qa = Qa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qa_params
      params.require(:qa).permit(:question, :name, :email, :other)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convention_helper.rb
module ConventionHelper
end

app/helpers/gurus_helper.rb
module GurusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/scaffolds_helper.rb
module ScaffoldsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/gurus/_form.html.erb
<%= simple_form_for(@guru) do |f| %>
  <%= f.error_notification %>
<div style ="margin:10px">

  <div class="form-inputs">
    

    <!-- Q1 -->
    <%= f.input :a1, :as => :text, :input_html => { :rows => 8}, label: "Being on the inside what do you think went well at the Instructor Convention?" %>
    <br>

    <!-- Q2 -->
    <%= f.input :a2, :as => :text, :input_html => { :rows => 8}, label: "What can be improved for the next conference?  (be specific & solutions are appreciated)"%>
    <br>
    
    <!-- Q3 -->

    <%= f.input :a3, :as => :text, :input_html => { :rows => 8}, label: "Do you have any suggestions for break out session topics or general session topics for the next conference?"%>
    <br>

    <!-- Q4 -->
    <%= f.input :a4, :as => :text, :input_html => { :rows => 8}, label: "Of the sessions you attended which were the top 3 you think were most beneficial to instructors?  (see agenda in app. to reference sessions again)"%>
    <br>

    <!-- Q5 -->
    <%= f.input :a5, :as => :text, :input_html => { :rows => 8}, label: "Tell us about a few experiences that stuck out to you with instructors at the convention & what feedback they shared with you? (constructive and positive)" %>
    <br>

    <!-- Q6 -->
    <%= f.input :a6, :as => :text, :input_html => { :rows => 8}, label: "What feedback have you been hearing post-convention? " %>
    <br>

    <!-- Q7 -->
    <%= f.input :a7, :as => :text, :input_html => { :rows => 8}, label: "What general ideas or suggestions do you have for the next convention? "%>
    <br>




<!--     <%= f.input :a8, label: "* Name(s)", input_html: {style: 'height:100px;'} %>
    <%= f.input :a9, label: "* Name(s)", input_html: {style: 'height:100px;'} %> -->
  </div>

 <button style ="background-color: #EC549E">
    <%= f.button :submit, "Submit" %>
  </button>
<% end %>

</div>

app/views/gurus/edit.html.erb
<h1>Editing Guru</h1>

<%= render 'form', guru: @guru %>

<%= link_to 'Show', @guru %> |
<%= link_to 'Back', gurus_path %>

app/views/gurus/index.html.erb
<p id="notice"><%= notice %></p>
<div style = "margin:20px">
<center>
  <br>
  <h4 style="color:#EC549E"> Guru Survey </h4>
</center>
<br>


<table style = "color:#EC549E">
  <thead>
    <tr>
      <th>Survey</th>
<!--       <th>A2</th>
      <th>A3</th>
      <th>A4</th>
      <th>A5</th>
      <th>A6</th>
      <th>A7</th> -->

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gurus.each do |guru| %>
      <tr>
        <td><%= guru.id %></td>
<!--         <td><%= guru.a2 %></td>
        <td><%= guru.a3 %></td>
        <td><%= guru.a4 %></td>
        <td><%= guru.a5 %></td>
        <td><%= guru.a6 %></td>
        <td><%= guru.a7 %></td>  -->
<!--         <td><%= guru.a8 %></td>
        <td><%= guru.a9 %></td> -->
        <td><%= link_to 'Show', guru %></td>
        <td><%= link_to 'Edit', edit_guru_path(guru) %></td>
        <td><%= link_to 'Destroy', guru, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_guru_path %>
</div>

app/views/gurus/new.html.erb
<center>
  <br>
  <h4 style="color:#EC549E"> Guru Survey </h4>
</center>
<br>
<br>

<%= render 'form', guru: @guru %>
<br>
<br>

<%#= link_to 'Back', gurus_path %>

app/views/gurus/show.html.erb
<p id="notice"><%= notice %></p>

<div style= "margin:10px">
<p>
  <i style="color:#EC549E">Being on the inside what do you think went well at the Instructor Convention?</i>
  <br>

  <%= @guru.a1 %>
</p>
<hr>

<p>
  <i style="color:#EC549E">What can be improved for the next conference?  (be specific & solutions are appreciated)</i>
  <br>

  <%= @guru.a2 %>
</p>
<hr>

<p>
  <i style="color:#EC549E">Do you have any suggestions for break out session topics or general session topics for the next conference?</i>
  <br>

  <%= @guru.a3 %>
</p>
<hr>

<p>
  <i style="color:#EC549E">Of the sessions you attended which were the top 3 you think were most beneficial to instructors?  (see agenda in app. to reference sessions again)</i>
  <br>

  <%= @guru.a4 %>
</p>
<hr>

<p>
  <i style="color:#EC549E">"Tell us about a few experiences that stuck out to you with instructors at the convention & what feedback they shared with you? (constructive and positive)</i>
  <br>
  <%= @guru.a5 %>
</p>
<hr>

<p>
  <i style="color:#EC549E">What feedback have you been hearing post-convention?</i>
  <br>

  <%= @guru.a6 %>
</p>
<hr>

<p>
  <i style="color:#EC549E">What general ideas or suggestions do you have for the next convention?</i>
  <br>
  <hr>

  <%= @guru.a7 %>
</p>

<br>
<br>

<!-- <p>
  <i>A8:</i>
  <%= @guru.a8 %>
</p>

<p>
  <i>A9:</i>
  <%= @guru.a9 %>
</p> -->

<%= link_to 'Edit', edit_guru_path(@guru) %> |
<%= link_to 'Back', gurus_path %>
</div>