config/routes.rb
Rails.application.routes.draw do

  resources :gurus
  resources :prizes
  resources :picks do
    collection { post :import}
  end

  
  resources :surveys
  resources :votes
  resources :scaffolds
  resources :choreo_regs


  resources :qas, :path => 'qa'

  get 'convention/venue'

  get 'convention/home'

  get 'convention/register'

  get 'convention/agenda_one'

  get 'convention/agenda_two'

  get 'convention/agenda_three'  

  get 'convention/winner'

  get 'convention/faq'

  get 'convention/sponsors'
  
  get  'convention/choreo_full'

  get 'pages/faq'

  get 'pages/congratulations'

  get 'pages/vote_counted'

  get 'tables/congrats'


  resources :tables
  

  root to: 'convention#home'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/Trip.rb
class Trip <ActiveRecord::Base

   CLASS_LIST = ["Sea Plane/Fly Fishing Tour", "Sea Plane/Nature Tour/Dinner"]

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choreo_reg.rb
class ChoreoReg < ApplicationRecord   

  validates_presence_of :song, 
                        :names,
                        :email,
                        :phone
end

app/models/guru.rb
class Guru < ApplicationRecord
end

app/models/pick.rb
class Pick < ApplicationRecord

belongs_to :pick, optional: true


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      pick = find_by_id(row['id']) || new
      pick.attributes = row.to_hash
      pick.save!
    end
  end




end

app/models/prize.rb
class Prize < ApplicationRecord

  has_many :picks
end

app/models/qa.rb
class Qa < ApplicationRecord

  validates_presence_of :question

end

app/models/survey.rb
class Survey < ApplicationRecord


  include Question


end

app/models/table.rb
class Table < ApplicationRecord

  validates_presence_of :company, 
                        :first_name, 
                        :middle_name, 
                        :last_name, 
                        :passport_id, 
                        :date_of_birth, 
                        :street_address, 
                        :city, 
                        :state, 
                        :zip_code, 
                        :mobile_phone, 
                        :email,
                        :preferred_airline




#     def self.search(search)
#   where("company ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR city ILIKE ? OR state ILIKE ? OR juneau_excursion ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
# end


    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |table|
            csv << table.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord

  
end

app/helpers/convention_helper.rb
module ConventionHelper
end

app/helpers/gurus_helper.rb
module GurusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/scaffolds_helper.rb
module ScaffoldsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-102750717-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   


    <!-- favicon -->

  <!--   <link rel="shortcut icon" href="https://s3-us-west-1.amazonaws.com/mont-general/highfitness/highfavicon.ico" type="image/x-icon">
    <link rel="icon" href="https://s3-us-west-1.amazonaws.com/mont-general/highfitness/highfavicon.ico" type="image/x-icon"> -->

    <!-- favicon end -->



    <%# google fonts %>

   <link href="https://fonts.googleapis.com/css?family=Open+Sans| Raleway" rel="stylesheet">

   
      <!-- google analytics code start-->

      <%= render 'shared/google_analytics' %>

    <!-- google analytics code end-->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">




      <title>High Instructor Convention</title>
        <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render 'shared/nav' %>
    <%= yield %>

    <%= render 'shared/alerts' %>

  </body>

  <%= render "shared/footer" %>
  
</html>

app/views/layouts/form.html.erb
<!DOCTYPE html>
<html>
  <head>
   


    <!-- favicon -->

   <!--  <link rel="shortcut icon" href="https://s3-us-west-1.amazonaws.com/mont-general/highfitness/highfavicon.ico" type="image/x-icon">
    <link rel="icon" href="https://s3-us-west-1.amazonaws.com/mont-general/highfitness/highfavicon.ico" type="image/x-icon">
 -->
    <!-- favicon end -->



    <%# google fonts %>

   <link href="https://fonts.googleapis.com/css?family=Open+Sans| Raleway" rel="stylesheet">

   
      <!-- google analytics code start-->

      <%= render 'shared/google_analytics' %>

    <!-- google analytics code end-->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">




      <title>High Instructor Convention</title>
        <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/upper_form' %>
  
    <%= yield %>

    <%= render 'shared/alerts' %>

 <%= render 'shared/lower_form' %>

  </body>

  
  
</html>

app/views/shared/_agenda_nav.html.erb
<%= link_to "Day One", convention_agenda_one_path %> 
<br>
<br>
<%= link_to "Day Two", convention_agenda_two_path %> 
<br>
<br>
<%= link_to "Day Three", convention_agenda_three_path %> 
<br>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "THANK YOU", sticky: false, time: 3500) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "HIGH FITNESS", sticky: false, time: 3500) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "THANK YOU", sticky: false, time: 3500) %>
<% end %>

app/views/shared/_footer.html.erb
<center>
  <div class= "footer">
              
 
<!--          If you have any additional questions please contact 
         with Next Level Events & Marketing. -->
        
      Questions -  Please contact Us
        <br>

       <!-- Kristen  &nbsp; <%#= number_to_phone "8014731024" %>  -->

   
         <a href="mailto: convention@highfitness.com?subject=High Fitness Instructor Convention">  Click Here to Email </a>

        <br>
  </div>
  </div>

    <hr>

      <div class="footer2">
        <center>

        | &copy;<%= Time.now.year %> Next Level Events & Marketing |

     
        <%= fa_icon "diamond" %> 
      <!--   <%#= fa_icon "heart" %>  --> 
        <%= fa_icon "thumbs-up" %>  
       <!--  <%#= fa_icon "cog" %>   -->
        <%= fa_icon "camera-retro" %>
        <%= fa_icon "globe" %>
        <%= fa_icon "plane" %>
<!--         <a href ='#' <%= fa_icon "twitter" %></a>
        <a href ='#'<%= fa_icon "facebook" %></a>
        <a href ='#'<%= fa_icon "instagram" %> </a>  -->
        <i class="fa fa-cog fa-spin fa-1x fa-fw"></i>| <!-- <a href='#'>Back to Top of page</a> -->
        </center>
        </div>
</center>

app/views/shared/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-102750717-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<%end %>  

app/views/shared/_high-footer.html.erb
  <div class ="high-footer">
    <img src= "https://s3-us-west-1.amazonaws.com/mont-general/highfitness/static1.squarespace.png" alt="Flowers in Chania" width="60%" >
  </div>

app/views/shared/_lower_form.html.erb
<br>

<div style="height:50px; color:white; background-color: #48484A; border: solid 4px #EC549E;width:100%">
</div>

app/views/shared/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #48484A;border: 2px solid #EC549E; border-radius: 11px 11px 0px 0px ;padding:4px 4px 4px 28px">
  <a class="navbar-brand " href="/convention/home" style="color:white"><img src= "https://iwxipdb153-flywheel.netdna-ssl.com/wp-content/uploads/2017/09/logo.png"  width="60px"></a>


  <button class="navbar-toggler custom-toggler " type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav  ml-auto">
      <a class="nav-item nav-link" href="/convention/home" >HOME </a>
      <a class="nav-item nav-link" href="/convention/venue" >LOCATION <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/convention/agenda_one" >LINE UP</a>  
      <a class="nav-item nav-link" href="/convention/faq" >FAQ's</a>
      <a class="nav-item nav-link" href="/convention/sponsors" >SPONSORS</a>
      <a class="nav-item nav-link" href="https://highfitnessconvention.regfox.com/high-fitness-convention-2019" target="_blank"><span6>REGISTER</span6></a>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
  </div>

</nav>

app/views/shared/_upper_form.html.erb
<div style="height:50px; color:white; background-color: #48484A; border: solid 4px #EC549E;width:100%">
</div>