config/routes.rb
Rails.application.routes.draw do

  resources :gurus
  resources :prizes
  resources :picks do
    collection { post :import}
  end

  
  resources :surveys
  resources :votes
  resources :scaffolds
  resources :choreo_regs


  resources :qas, :path => 'qa'

  get 'convention/venue'

  get 'convention/home'

  get 'convention/register'

  get 'convention/agenda_one'

  get 'convention/agenda_two'

  get 'convention/agenda_three'  

  get 'convention/winner'

  get 'convention/faq'

  get 'convention/sponsors'
  
  get  'convention/choreo_full'

  get 'pages/faq'

  get 'pages/congratulations'

  get 'pages/vote_counted'

  get 'tables/congrats'


  resources :tables
  

  root to: 'convention#home'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/Trip.rb
class Trip <ActiveRecord::Base

   CLASS_LIST = ["Sea Plane/Fly Fishing Tour", "Sea Plane/Nature Tour/Dinner"]

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choreo_reg.rb
class ChoreoReg < ApplicationRecord   

  validates_presence_of :song, 
                        :names,
                        :email,
                        :phone
end

app/models/guru.rb
class Guru < ApplicationRecord
end

app/models/pick.rb
class Pick < ApplicationRecord

belongs_to :pick, optional: true


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      pick = find_by_id(row['id']) || new
      pick.attributes = row.to_hash
      pick.save!
    end
  end




end

app/models/prize.rb
class Prize < ApplicationRecord

  has_many :picks
end

app/models/qa.rb
class Qa < ApplicationRecord

  validates_presence_of :question

end

app/models/survey.rb
class Survey < ApplicationRecord


  include Question


end

app/models/table.rb
class Table < ApplicationRecord

  validates_presence_of :company, 
                        :first_name, 
                        :middle_name, 
                        :last_name, 
                        :passport_id, 
                        :date_of_birth, 
                        :street_address, 
                        :city, 
                        :state, 
                        :zip_code, 
                        :mobile_phone, 
                        :email,
                        :preferred_airline




#     def self.search(search)
#   where("company ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR city ILIKE ? OR state ILIKE ? OR juneau_excursion ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
# end


    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |table|
            csv << table.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord

  
end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  before_action :set_qa, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "admin", password: "Kristen15", except: [ :new, :create ]

layout 'form'

  # GET /qas
  # GET /qas.json
  def index
    @qas = Qa.all
    @count= Qa.all.count
  end

  # GET /qas/1
  # GET /qas/1.json
  def show
  end


  # GET /qas/new
  def new
    @qa = Qa.new
  end

  # GET /qas/1/edit
  def edit
  end

  # POST /qas
  # POST /qas.json
  def create
    @qa = Qa.new(qa_params)

    respond_to do |format|
      if @qa.save
        format.html { redirect_to pages_congratulations_path, notice: 'Your Question was submitted' }
        format.json { render :show, status: :created, location: @qa }
      else
        format.html { render :new }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qas/1
  # PATCH/PUT /qas/1.json
  def update
    respond_to do |format|
      if @qa.update(qa_params)
        format.html { redirect_to @qa, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @qa }
      else
        format.html { render :edit }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qas/1
  # DELETE /qas/1.json
  def destroy
    @qa.destroy
    respond_to do |format|
      format.html { redirect_to qas_url, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qa
      @qa = Qa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qa_params
      params.require(:qa).permit(:question, :name, :email, :other)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy, :faq]


  http_basic_authenticate_with name: "admin", password: "Kristen15", except: [:new, :congrats, :create]


def congrats
end

  # GET /tables
  # GET /tables.json
  def index

   
      @tables = Table.all
      respond_to do |format|
        format.html
        format.csv{ send_data @tables.to_csv }
        format.xls{ send_data @tables.to_csv(col_sep: "\t") }
      
    end


  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json 
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        NotifyMailer.notify_kristen(@table).deliver
        format.html { redirect_to tables_congrats_path, notice: "CONGRATULATIONS! You've successfully completed registration." }
      
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Registration was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:company, :passport_id, :first_name, :middle_name, :last_name, :date_of_birth, :street_address, :city, :state, :zip_code, :mobile_phone, :email, :preferred_airline, :frequent_flyer_number, :preferred_flight_date, :preferred_departure_time_period, :preferred_departure_airport_code, :seat_preference, :food_allergies, :number_of_beds_requested, :companion, :medical, :additional_comments, )
    end
end

app/helpers/convention_helper.rb
module ConventionHelper
end

app/helpers/gurus_helper.rb
module GurusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/scaffolds_helper.rb
module ScaffoldsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/tables/_form.html.erb
<%= simple_form_for(table) do |f| %>
  <% if table.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

   
      <% table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
   
    </div>
  <% end %>

<br>
<div style= "color: #167495">
  <center> 
<h3>
  Please provide the following information for "each" individual attendee 
</h3>


</div>
<hr>
<br>

<div class = "grey">
<div class = "row">

  <div class = "col-sm-6">
    <h3 style="color: #12988B;"> Attendee Information:</h3>
      <br>
          <%= f.input :company,  label: "Company Name", placeholder: "*  Required Field"  %>
          <%= f.input :passport_id, label: "Passport Number",  placeholder: "*  Required Field"  %>
          <%= f.input :preferred_airline, label: "Passport Expiration Date",  placeholder: "*  Required Field         Passport Expiraton Date"  %>
          <%= f.input :date_of_birth, label: "Date of Birth",  placeholder: "*  Required Field  MM/DD/YYYY" %>

          <%= f.input :first_name, label: "First Name",  placeholder: "*  Required Field              As printed on Passport" %>
          <%= f.input :middle_name, label: "Middle Name",  placeholder: "*  Required Field             As printed on Passport" %>
          <%= f.input :last_name, label: "Last Name",  placeholder: "*  Required Field             As printed on Passport" %>
          <%= f.input :street_address, label: "Street Address", placeholder: "*  Required Field" %>
          <%= f.input :city,  placeholder: "*  Required Field" %>
          <%= f.input :state,  placeholder: "*  Required Field" %>
          <%= f.input :zip_code, label: "Zip Code", placeholder: "*  Required Field" %>
          <%= f.input :mobile_phone, label: "Mobile Phone",  placeholder: "*  Required Field" %>
          <%= f.input :email, label: "Email Address",  placeholder: "*  Required Field" %>


      <h3 style="color: #12988B;"> Flight Information:</h3>
      <br>


        <div class="field">
          <%= f.label :frequent_flyer_number, "Frequent Flyer Number" %>
          <%= f.text_field :frequent_flyer_number, class: 'form-control' %>
        </div>



        <%= f.input :seat_preference, label: "Airplane Seat Preference",  placeholder: "*  ie; aisle, window..." %>
        <%= f.input :companion, label: "Companion Name" %>

  </div>








  <div class = "col-sm-6">
      <h3 style="color: #12988B;"> Other information:</h3>
        <br>

      <div class="field">
        <%= f.label :food_allergies, "Food Allergies"%>
        <%= f.text_field :food_allergies,class: 'form-control' %>
      </div>
      
      <br>

      <div class="field">
        <%= f.input :medical, label: "Medical Conditions" %>
      </div>

      <div class="field">
        <%= f.label :additional_comments, "Additional Comments" %>
        <%= f.text_area :additional_comments ,class: 'form-control', rows: 17 %>
      </div>
        <br>
        <br>
        <%= f.button :submit, 'Click Here to Submit',class: "btn btn-primary"  %>
</div>
<br>

  </div>
</div>
</div>
</center>
  
<% end %>

app/views/tables/congrats.html.erb
<center>

CONGRATULATIONS! Your registration has been successfully recorded! <br>
We will reach out to you with further details as we get closer to departure. <br>
We look forward to seeing you in Emerald Bay!
  
<br>
<br>
<%= image_tag("https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img7.jpg", style: 'width:80%')%>
<br>
If you'd like to register another attendee click below.
<br>
<br>


      <div >
        <%= link_to 'Add New Attendee', new_table_path, class: "btn btn-primary"%> 
    </div>


<br>
<br>
<br>
<br>
<br>
</center>

app/views/tables/edit.html.erb
<h1>Edit Your Information</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<div style="background-color:#f6f6f6">
<br>
<h2><center>- Registered Attendee Report -</center></h2>

<br>
</div>
<br>

<br>Attendee Count: <%= @tables.count %>

 

<br>
<br>

  <div style="overflow-x:auto;">
    <table >

      <thead>
          <th>Full Record</th>
          <th>Company </th>
          <th>Passport </th>
          <th>First </th>
      <!--     <th>Middle </th> -->
          <th>Last </th>
      <!--     <th>DOB</th>
          <th>Address</th> -->
          <th>City</th>
          <th>State</th>
         <!--  <th>Zip code</th> -->
          <th>Phone</th>
          <th>Email</th>
    <!--       <th>Preferred airline</th>
          <th>Frequent flyer number</th>
          <th>Preferred flight date</th>
          <th>Preferred departure time period</th>
          <th>Preferred departure airport code</th>
          <th>Seat preference</th>
          <th>Food allergies</th>
          <th>Number of beds requested</th> -->
          <th>Companion </th>
      
          <th>Edit </th>
          <th>Delete </th>
     
         
          

         <!--  <th>Medial Conditions<th> -->
         <!--  <th>Additional Comments<th> -->
    
        </tr>
      </thead>

      <tbody>
        <% @tables.each do |table| %>
          <tr>

            <td><%= link_to 'Detailed info', table %></td>
            <td><%= table.company.upcase %></td>
            <td><%= table.passport_id %></td>
            <td><%= table.first_name.titleize %></td>
          <!--   <td><%= table.middle_name %></td> -->
            <td><%= table.last_name.titleize %></td>
     <!--        <td><%= table.date_of_birth %></td>
            <td><%= table.street_address %></td> -->
            <td><%= table.city.titleize %></td>
            <td><%= table.state.upcase %></td>
            <!-- <td><%= table.zip_code %></td> --> 
            <td><%= table.mobile_phone %></td>
            <td><%= table.email %></td>
     <!--        <td><%= table.preferred_airline %></td>
            <td><%= table.frequent_flyer_number %></td>
            <td><%= table.preferred_flight_date %></td>
            <td><%= table.preferred_departure_time_period %></td>
            <td><%= table.preferred_departure_airport_code %></td>
            <td><%= table.seat_preference %></td>
            <td><%= table.food_allergies %></td>
            <td><%= table.number_of_beds_requested %></td> -->
            <td><%= table.companion.titleize %></td> 
        

    <!--         <td><%= table.medical %></td> 
            <td><%= table.additional_comments %></td>   -->
            
            <td><%= link_to 'Edit', edit_table_path(table) %></td>
            <td><%= link_to 'Delete', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
<br>
<br>


<p>
Click to download Attendee Report: <br>  
<%= link_to "EXCEL REPORT", tables_path(format: "xls") %>

</p>

<br>

app/views/tables/new.html.erb
<%= link_to  pages_faq_path do %>
<div class="faq-button">
Trip Overview
</div>
<%end%>

<hr>
<br>


          <h3 style= "color: #167495;">dentist DIRECT</h3>
          <h3 style= "color: #167495;">Emerald Bay Bahamas</h3>
          <h3 style= "color: #167495;"> February 8-15th</h3>

  <br>

<center>
  <div class="parent"
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 h-auto" src="https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img1.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img2.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img3.jpg" alt="Third slide">
    </div>
        <div class="carousel-item">
      <img class="d-block w-100" src="https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img4.jpg"" alt="Fourth slide">
    </div>

        <div class="carousel-item">
      <img class="d-block w-100" src="https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img5.jpg" alt="Fifth slide">
    </div>

        <div class="carousel-item">
      <img class="d-block w-100" src="https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img6.png" alt="Sixth slide">
    </div>
  </div>
  </div>
</div>

</center>



  
<%= render 'form', table: @table %>
<br>
<hr>


<%#= link_to 'Click here to go Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<h7 style= "color:#0275d8;">Below is the information you've submitted:</h7>
<br>
<br>
 <h7>If you would like to change anything click  <font color="#0275d8">"Edit Information"</font>  
 
          -OR- 

if you'd like to register your travel companion click  <font color="#0275d8">""Add New Attendee" </font>  </h7>
<br>
<br>

<hr>
<hr>
<br>

<div class = "row">
 
  <div class = "col-md-4">
  
      Registation Information for : 
    <p style= "color:#0275d8;"> <%= @table.first_name.upcase %> <%= @table.last_name.upcase %></p>
  </div>

      <div class= "col-md-4">
         <%= link_to 'Edit Information', edit_table_path(@table), class: "btn btn-primary" %> 
       </div>


    <div class= "col-md-4">
        <%= link_to 'Add New Attendee', new_table_path, class: "btn btn-primary"%> 
    </div>

    
  </div>
<hr>

<hr>


<div class= "row">

  <div class= "col-md-4">

    <p>
      <strong class= "cool">Company:</strong>
      <%= @table.company %>
    </p>


    <p>
      <strong class= "cool">Passport:</strong>
      <%= @table.passport_id %>
    </p>

    <p>
      <strong class= "cool">Passport Expiration:</strong>
      <%= @table.preferred_airline %>
    </p>

    <p>
      <strong class= "cool">First Name:</strong>
      <%= @table.first_name %>
    </p>

    <p>
      <strong class= "cool">Middle Name:</strong>
      <%= @table.middle_name %>
    </p>

    <p>
      <strong class= "cool">Last Name:</strong>
      <%= @table.last_name %>
    </p>

    <p>
      <strong class= "cool">Date of Birth:</strong>
      <%= @table.date_of_birth %>
    </p>

    <p>
      <strong class= "cool">Street Address:</strong>
      <%= @table.street_address %>
    </p>

    <p>
      <strong class= "cool">City:</strong>
      <%= @table.city %>
    </p>

    <p>
      <strong class= "cool">State:</strong>
      <%= @table.state %>
    </p>

    <p>
      <strong class= "cool">Zip Code:</strong>
      <%= @table.zip_code %>
    </p>

    <p>
      <strong class= "cool">Mobile Phone:</strong>
      <%= @table.mobile_phone %>
    </p>

    <p>
      <strong class= "cool">Email Address:</strong>
      <%= @table.email %>
    </p>

  </div>

    <!-- Image in center -->
     <div class= "col-md-4">

        <%= image_tag "https://s3-us-west-1.amazonaws.com/mont-general/Emerald/Img1.jpg", style: "width:300px; margin-bottom:30px" %>

     </div>



  <div class= "col-md-4">


  

    <p>
      <strong class= "cool">Frequent Flyer Number:</strong>
      <%= @table.frequent_flyer_number %>
    </p>

  

    <p>
      <strong class= "cool">Seat Preference:</strong>
      <%= @table.seat_preference %>
    </p>


    <p>
      <strong class= "cool">Travel Companion Name:</strong>
      <%= @table.companion %>
    </p>

 <!--    <p>
      <strong class= "cool">Excursion Choice:</strong>
      <%= @table.juneau_excursion %>
    </p> -->

    <p>
      <strong class= "cool">Food Allergies:</strong>
      <%= @table.food_allergies %>
    </p>


    <p>
      <strong class= "cool">Medical Conditions:</strong>
      <%= @table.medical %>
    </p>

    <p>
      <strong class= "cool">Additional Comments:</strong>
      <%= @table.additional_comments %>
    </p>
  </div>
</div>

<hr>