config/routes.rb
Rails.application.routes.draw do

  resources :gurus
  resources :prizes
  resources :picks do
    collection { post :import}
  end

  
  resources :surveys
  resources :votes
  resources :scaffolds
  resources :choreo_regs


  resources :qas, :path => 'qa'

  get 'convention/venue'

  get 'convention/home'

  get 'convention/register'

  get 'convention/agenda_one'

  get 'convention/agenda_two'

  get 'convention/agenda_three'  

  get 'convention/winner'

  get 'convention/faq'

  get 'convention/sponsors'
  
  get  'convention/choreo_full'

  get 'pages/faq'

  get 'pages/congratulations'

  get 'pages/vote_counted'

  get 'tables/congrats'


  resources :tables
  

  root to: 'convention#home'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/Trip.rb
class Trip <ActiveRecord::Base

   CLASS_LIST = ["Sea Plane/Fly Fishing Tour", "Sea Plane/Nature Tour/Dinner"]

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choreo_reg.rb
class ChoreoReg < ApplicationRecord   

  validates_presence_of :song, 
                        :names,
                        :email,
                        :phone
end

app/models/guru.rb
class Guru < ApplicationRecord
end

app/models/pick.rb
class Pick < ApplicationRecord

belongs_to :pick, optional: true


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      pick = find_by_id(row['id']) || new
      pick.attributes = row.to_hash
      pick.save!
    end
  end




end

app/models/prize.rb
class Prize < ApplicationRecord

  has_many :picks
end

app/models/qa.rb
class Qa < ApplicationRecord

  validates_presence_of :question

end

app/models/survey.rb
class Survey < ApplicationRecord


  include Question


end

app/models/table.rb
class Table < ApplicationRecord

  validates_presence_of :company, 
                        :first_name, 
                        :middle_name, 
                        :last_name, 
                        :passport_id, 
                        :date_of_birth, 
                        :street_address, 
                        :city, 
                        :state, 
                        :zip_code, 
                        :mobile_phone, 
                        :email,
                        :preferred_airline




#     def self.search(search)
#   where("company ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR city ILIKE ? OR state ILIKE ? OR juneau_excursion ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
# end


    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |table|
            csv << table.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord

  
end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  before_action :set_qa, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "admin", password: "Kristen15", except: [ :new, :create ]

layout 'form'

  # GET /qas
  # GET /qas.json
  def index
    @qas = Qa.all
    @count= Qa.all.count
  end

  # GET /qas/1
  # GET /qas/1.json
  def show
  end


  # GET /qas/new
  def new
    @qa = Qa.new
  end

  # GET /qas/1/edit
  def edit
  end

  # POST /qas
  # POST /qas.json
  def create
    @qa = Qa.new(qa_params)

    respond_to do |format|
      if @qa.save
        format.html { redirect_to pages_congratulations_path, notice: 'Your Question was submitted' }
        format.json { render :show, status: :created, location: @qa }
      else
        format.html { render :new }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qas/1
  # PATCH/PUT /qas/1.json
  def update
    respond_to do |format|
      if @qa.update(qa_params)
        format.html { redirect_to @qa, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @qa }
      else
        format.html { render :edit }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qas/1
  # DELETE /qas/1.json
  def destroy
    @qa.destroy
    respond_to do |format|
      format.html { redirect_to qas_url, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qa
      @qa = Qa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qa_params
      params.require(:qa).permit(:question, :name, :email, :other)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choreo_regs_helper.rb
module ChoreoRegsHelper
end

app/helpers/convention_helper.rb
module ConventionHelper
end

app/helpers/gurus_helper.rb
module GurusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/scaffolds_helper.rb
module ScaffoldsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/qas/_form.html.erb
<%= simple_form_for(@qa) do |f| %>
  <%= f.error_notification %>

 <div style= "margin:15px">
      <div class="form-inputs">
        <%= f.input :question, :as => :text, :input_html => {:rows => 3}  %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%#= f.input :other %>
      </div>

      <button style= "background-color:#EC549E;color:white">
        <%= f.button :submit, "Submit" %>
      </button>
    <% end %>
     
     <br>
</div>

app/views/qas/congrats.html.erb
Congrats

app/views/qas/edit.html.erb
<h1>Editing Qa</h1>

<%= render 'form', qa: @qa %>

<%= link_to 'Show', @qa %> |
<%= link_to 'Back', qas_path %>

app/views/qas/index.html.erb
<div style = "padding:20px">
      <p id="notice"><%= notice %></p>

      <center>
      <h3>Conference Questions</h3>
      </center>
 
   

      <div style= "margin:20px">
        <table >
          <thead >
            <tr>
              <th style= "background-color: #EC549E">Question</th>
              <center>
              <th style= "background-color: #EC549E">Name</th>
      <!--         <th style= "background-color: #EC549E">Email</th>
              <th style= "background-color: #EC549E">Other</th> -->
              <th style= "background-color: #EC549E" colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @qas.each do |qa| %>
              <tr>
                <td style= "text-align: left"><%= qa.question %></td>
                <td><%= qa.name %></td>
          <!--       <td><%= qa.email %></td>
                <td><%= qa.other %></td> -->
                <td><%= link_to 'Show', qa %></td>
                <!-- <td><%#= link_to 'Edit', edit_qa_path(qa) %></td> -->
                <td><%= link_to 'Delete', qa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </center>
      <br>



      <%= link_to 'Ask Question', new_qa_path %>

      </div>

</div>

app/views/qas/new.html.erb
<br>

<center>
<h4 style = "color:#EC549E">Convention Question</h4>
</center>
<%= render 'form', qa: @qa %>

<%#= link_to 'Back', qas_path %>

app/views/qas/show.html.erb
<p id="notice"><%= notice %></p>

<div style= "margin:25px">
<div>
  <strong>Attendee:</strong>
  <%= @qa.name %>

<br>

  <strong>Email:</strong>
  <%= @qa.email %>
</div>

<hr>

<p>
  <strong>Question:</strong>
  <br>
  "<%= @qa.question %>"
</p>


<!-- <p>
  <strong>Other:</strong>
  <%#= @qa.other %>
</p> -->

<hr>
<br>
<%= link_to 'Edit', edit_qa_path(@qa) %> |
<%= link_to 'Back', qas_path %>
</div>